### ISSUE TITLE
Can't remove successful uploads

### ISSUE THREAD

**Issue by aschempp** [terminal42/contao-fineuploader#38]
If I uploaded a file (without submitting the form), I can't remove the download (to maybe replace it with something else).

There seems to be an invisible `qq-upload-delete` button, maybe that's a configuration?

**Comment by qzminski** [comment]
I assume you mean the frontend. The mentioned button is provided by the FineUploader and does only affect the FineUploader stuff itself, i.e. ```qq-upload-list```. However we use a custom hidden input to store the actual file path values.

See the backend for the reference. There is a custom delete button which updates the hidden input field value. The same button is also available for frontend but not for "fresh" uploads though. If you e.g. upload the image, submit the form ```with errors``` then after the page reload you should see the appropriate delete button next to each file (as now the form field has a value).

The backend has that button for "fresh" uploads as well because there we use AJAX to generate the file list which is not the case in the frontend now. Shall we provide the similar AJAX implementation in frontend?

**Comment by aschempp** [comment]
I noticed the delete button after form submission, and that works fine. But why is the remove-Button not visible after upload (without submitting the form) ?

**Comment by qzminski** [comment]
Because we do not perform an AJAX request in the frontend to generate the file list. Until now it was up to developer because of variety of possible implementations.

**Comment by aschempp** [comment]
What do you mean by *until now*?

**Comment by qzminski** [comment]
Until today it is up to developer.

**Comment by aschempp** [comment]
And how is the *developer* by using the form generator supposed to "fix" this??

**Comment by qzminski** [comment]
If you want me to create the default AJAX implementation please provide details such as JS library used whether it's jQuery or MooTools to handle AJAX requests, items sorting and other potential stuff.

**Comment by aschempp** [comment]
Does the frontend also use the hidden input field **before submitting the form**? If not it should be possible to remove the item from fineuploader itself?

**Comment by qzminski** [comment]
Yes it does use the hidden field. The handler is the same for backend and frontend except the fact that in the backend there is an AJAX request made to reload the widget.

**Comment by aschempp** [comment]
@qzminski you told me this is solved in the new version? Guess we should assign the milestone and close it then?

**Comment by seibtph** [comment]
@qzminski Do you have a tip on how to integrate the deletion of files? Because I need this for a web project, but I have not found a solution.

**Comment by qzminski** [comment]
@seibtph I suggest that you either check the FineUploader documentation or upload files to the temporary folder that is periodically purged e.g. by some cron job.
