### ISSUE TITLE
uploaderLimit Field not available in "Fine uploader" Form Field

### ISSUE THREAD

**Issue by theDyingMountain** [terminal42/contao-fineuploader#73]
The uploaderLimit setting is described in the docs, but is not available in the Fine uploader Formfield in the Form Generator. Is there any reason?

**Comment by ngdot** [comment]
It is there, but named differently (limit). The default value is `1`. If you choose "Multiple choice" in the form generator its possible to change that value (theoretically). But sadly, the value is not set correctly into the json/javascript code, that is responsible for the field handling. It always saves as `null` instead of the number you've write in the form generator. So thats definitely a bug!

As a small workarround you can copy the json/javascript code output of your settings from the frontend (script tag under the upload field) and write it manuelly into a new template (fineuploader_frontend.html5).

**Comment by fritzmg** [comment]
Fixed via f853095
