### ISSUE TITLE
File upload starts session and causes invalid request token

### ISSUE THREAD

**Issue by richardhj** [terminal42/contao-fineuploader#86]
It looks like the file upload causes issues that are described in contao/contao#2820.

Steps to reproduce are:
- Open a form with FineUploader (cookies present in the browser are, among others, the csrf_https-contao_csrf_token, ISOTOPE_TEMP_CART, _ga*)
- Upload a file using FineUploader, the response starts the PHP session and sets a cookie
- The cookie PHPSESSID is now present in the browser
- The form cannot be submitted

<img width="425" alt="Screenshot 2022-06-02 at 08 33 09" src="https://user-images.githubusercontent.com/1284725/171568572-e88752c9-6254-46c9-9896-82f0f84fc8f0.png">

**Comment by fritzmg** [comment]
Generally this can happen in Contao, if you are on a page with a form and any AJAX request will cause any subsequent request to require to have a CSRF token.

**Comment by richardhj** [comment]
So we need to start the session when the form is generated?

**Comment by fritzmg** [comment]
You mean the FineUploader widget should always start a session? That would certainly fix it. Not sure what the best or most "correct" solution is though. The AJAX request could also return a REQUEST_TOKEN so that the JavaScript can insert it into the form. However that sounds like something that Contao should provide a sort of API for in general 🤔

**Comment by richardhj** [comment]
As discussed, the missing session is the issue, so this is what I implemented in the project:

```php
<?php

namespace App\EventListener;

use Contao\CoreBundle\ServiceAnnotation\Hook;
use Contao\Widget;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * @Hook("parseWidget")
 */
class ParseWidgetListener
{
    private $session;

    public function __construct(Session $session)
    {
        $this->session = $session;
    }

    public function __invoke(string $buffer, Widget $widget): string
    {
        if (!$this->session->isStarted()) {
            $this->session->set('foo', uniqid());
        }

        return $buffer;
    }
}
```

**Comment by RoToK4** [comment]
Hello,

I would like to take up the problem again.

I have a form in which the fineuploader is implemented.

The following scenario:
I open the page with the form, delete all browser cookies and reload the page.

Then I fill out the form and upload a file. The following cookies are then set:

PHPSESSID / csrf_https-contao_csrf_token
The form cannot be submitted - error message:

_Invalid request token
What is the problem?
The request token could not be validated._

If I rebuild the form into two pages (extension: mp_forms), and the fineuploader is on the second page: Then the form is submitted perfectly.

In a second project we have the fineuploader behind a customer login (also on a one-page form), and it works there too without any problems.

I tested the above code, but the problem remains. I also created a "PHPSESSID" cookie when loading the page - this wasn't the solution either, because the self-created cookie is simply overwritten after the upload.

```
if (session_id() == "") {
            session_start();
        }

        if (!isset($_COOKIE["PHPSESSID"])) {
            setcookie("PHPSESSID", session_id(), [
                "expires' => time() + 3600, // 1 Stunde
                "path" => "/",
                "domain" => "", // optional: domain setzen
                "secure" => true, // falls HTTPS verwendet wird
                "httponly" => true,
                "samesite" => "Lax" // oder 'Strict'
            ]);
        }
```

Is there any way/solution to make the fineuploader work in a one-page form without prior login?

Contao version: 4.13.45
fineupload version: 3.4.11

**Comment by RoToK4** [comment]
I have now implemented the following solution and it works for us:
```
<?php

// src/EventListener/SessionAndCsrfListener.php

namespace App\EventListener;

use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

class SessionAndCsrfListener
{
    private $csrfTokenManager;
    private $session;

    public function __construct(CsrfTokenManagerInterface $csrfTokenManager, SessionInterface $session)
    {
        $this->csrfTokenManager = $csrfTokenManager;
        $this->session = $session;
    }

    public function onKernelRequest(RequestEvent $event)
    {
        $request = $event->getRequest();

        // Start the session if it is not already started
        if (!$this->session->isStarted()) {
            $this->session->start();
        }

        // Set the PHPSESSID cookie if not already set
        if (!isset($_COOKIE["PHPSESSID"])) {
            setcookie("PHPSESSID", $this->session->getId(), [
                "expires" => time() + 3600, // 1 hour
                "path" => "/",
                "domain" => "", // set your domain if needed
                "secure" => true, // set to true if using HTTPS
                "httponly" => true,
                "samesite" => "Lax" // or "Strict"
            ]);
        }

        // Generate and set the CSRF token cookie if not already set
        if (!isset($_COOKIE["csrf_https-contao_csrf_token"])) {
            $csrfToken = $this->csrfTokenManager->getToken("contao_csrf_token")->getValue();
            setcookie("csrf_https-contao_csrf_token", $csrfToken, [
                "expires" => time() + 3600, // 1 hour
                "path" => "/",
                "domain" => "", // set your domain if needed
                "secure" => true, // set to true if using HTTPS
                "httponly" => true,
                "samesite" => "Lax" // or "Strict"
            ]);
        }
    }
}
```

**Comment by fritzmg** [comment]
You should not start a session on every request. Especially not this way.

**Comment by RoToK4** [comment]
Ok, thanks for the feedback, but what is the better solution to fix the problem?

**Comment by fritzmg** [comment]
See the previous comment: https://github.com/terminal42/contao-fineuploader/issues/86#issuecomment-1144609737

The correct solution is still unclear.

**Comment by fritzmg** [comment]
@RoToK4 @richardhj can you confirm that this issue only occurs if **Enable chunking** is enabled?

**Comment by fritzmg** [comment]
If yes, you can test `dev-hotfix/init-session` (#113)

**Comment by RoToK4** [comment]
@fritzmg No, in my case, **Enable chunking** is disabled

**Comment by fritzmg** [comment]
I cannot reproduce the issue without that option, as the fineuploader only uses the session for chunked uploads.

**Comment by fritzmg** [comment]
I have merged and released https://github.com/terminal42/contao-fineuploader/pull/113 in any case as I was able to reproduce the issue with chunked uploading (and only then) and #113 fixes that.

I am closing this for now. If a reproduction without chunked uploading arises we can re-open it again (or open a new issue).
